spring:
  datasource:
    url: jdbc:mysql://192.168.3.73:3306/dph?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: Gah6kuP7ohfio4
    druid:
      initial-size: 1
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      conconnectionInitSqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
